## notify: Restart Docker
- set_fact:
    daemon_config: "{{ docker_daemon_settings | to_nice_json(indent=2) }}"

- name: Generate Docker daemon config
  copy:
    content: "{{ daemon_config }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: Restart Docker