---
# tasks file for docker
- name: Install Docker dependencies
  apt:
    state: present
    update_cache: yes
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-apt

- name: Add docker GPG Key
  tags: ['docker', 'install_docker']
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu "{{ ubuntu_release }}" stable
    
- name: Install Docker
  apt:
    state: present
    update_cache: yes
    pkg:
      - "docker-ce={{ docker-ce-version }}"
      - "docker-ce-cli={{ docker-ce-cli-version }}"
      - containerd.io 
      - docker-compose-plugin



