---
# tasks file for docker
- name: Install Docker
  include_tasks: ./install.yml

- name: Install Nvidia container toolkit
  include_tasks: ./nvidia.yml
  when: install_nvidia_toolkit

- name: Configure Docker
  import_tasks: ./configure.yml

- name: Harden Docker
  import_tasks: ./harden.yml
  