
# Include the roles from https://github.com/dev-sec/ansible-collection-hardening
- name: OS Hardening
  ansible.builtin.include_role:
    name: devsec.hardening.os_hardening
 
- name: SSH Hardening
  ansible.builtin.include_role:
    name: devsec.hardening.ssh_hardening

# Custom Hardening
