---
# tasks file for berglucht.common

- name: Create users
  include_tasks: ./users.yml

- name: Firewall
  import_tasks: ./firewall.yml

- name: Install packages
  import_tasks: ./install.yml

- name: Sysctl
  import_tasks: ./hardening.yml

