---
# tasks file for berglucht.common

- name: Create users
  include_tasks: ./users.yml
  tags: ['common', 'users']
  
- name: Hardening 
  include_tasks: ./hardening.yml
  tags: ['common', 'os-hardening']